# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ExamplePod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExamplePod
  
#  pod 'OSIM', :git => 'https://github.com/macMaintain123profil/OCSIM.git'
  pod 'OCSIM', :path => '../'

  target 'ExamplePodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExamplePodUITests' do
    # Pods for testing
  end

end
